# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

array_array2 <- function(in) {
    .Call(`_LABuilder_array_array2`, in)
}

printResults_wrapper <- function(p_, array_, success_) {
    .Call(`_LABuilder_printResults_wrapper`, p_, array_, success_)
}

rcpp_hello_world <- function() {
    .Call(`_LABuilder_rcpp_hello_world`)
}

